In [2]:
import scipy.io
import open3d
import io
import os
import numpy as np

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [ ]:
username= "MirnaL"
file_path = "C:/Users/" + username + "/Desktop/zadatak/lidar_sample"
file_names = os.listdir(file_path)

one_array = np.empty((0, 3))

for filename in file_names:
    print(filename)
    with io.open(file_path + "/" + filename, "rb") as f:
        try:
            mat_contents = scipy.io.loadmat(f)
        except (ValueError, OSError):
            _logger.error("Point cloud " + str(filename) + " is corrupted.") 
        if "worldCoordinates" in mat_contents: 
            point_cloud = mat_contents["worldCoordinates"]
        else: 
            point_cloud = mat_contents["lidarPts"]
    
    one_array = np.vstack((one_array, point_cloud))

            
new_pcd = open3d.geometry.PointCloud()
new_pcd.points = open3d.utility.Vector3dVector(one_array)
open3d.visualization.draw_geometries([new_pcd])

#spremanje 3d objekta u .ply datoteku
open3d.io.write_point_cloud("output.ply", new_pcd)

# pcd = open3d.io.read_point_cloud("output.ply")
# open3d.visualization.draw_geometries([pcd])

In [15]:
print(mat_contents["lidarPts"])

[[-117.14186      3.4665804    1.8165971]
 [-119.9267       3.565396     3.876401 ]
 [-120.67767      3.6150217   10.105863 ]
 ...
 [  -1.8972076    0.4535299    0.9503895]
 [-119.80833      3.2849727    1.7947791]
 [-119.33052      3.3040166    3.85394  ]]


In [21]:
print(new_pcd.points)

std::vector<Eigen::Vector3d> with 218816 elements.
Use numpy.asarray() to access data.


In [19]:
print(np.asarray(new_pcd.points))

[[-117.14186096    3.46658039    1.8165971 ]
 [-119.92669678    3.56539607    3.87640095]
 [-120.67767334    3.61502171   10.10586262]
 ...
 [  -1.89720762    0.45352989    0.9503895 ]
 [-119.80832672    3.28497267    1.79477906]
 [-119.33052063    3.30401659    3.85394001]]
